/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.components;

import com.rameses.rcp.control.XComponentPanel;
import com.rameses.rcp.ui.annotations.ComponentBean;

/**
 *
 * @author dell
 */
@ComponentBean("tagabukid.components.SelectMonthModel")
public class SelectMonth extends XComponentPanel {

    /**
     * Creates new form SelectMonth
     */
    public SelectMonth() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xComboBox1 = new com.rameses.rcp.control.XComboBox();

        setLayout(new java.awt.BorderLayout());

        xComboBox1.setExpression("#{item.title}");
        xComboBox1.setItemKey("id");
        xComboBox1.setItems("monthList");
        xComboBox1.setName("month"); // NOI18N
        add(xComboBox1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox xComboBox1;
    // End of variables declaration//GEN-END:variables
}
